name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2

            # Install Deps
            - name: Installing CMake and Bazel
              run: |
                  sudo sh install_bazel.sh
                  sudo sh install_cmake.sh

            # Build Bazel Target
            - name: Building Bazel PyTorch Target
              run: |
                  cd bazel && bazel build :torch_test

            # Build CMake Target
            - name: Building CMake PyTorch Target
              run: |
                  cd cmake
                  mkdir -p build
                  cd build && cmake .. && cmake --build
